/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Orphanage.Finance;

import Business.Child.Child;
import Business.Child.ChildDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Orphanage.FinanceOrphanageOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FinanceCCWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rao.sid
 */
public class FinanceOrphProcessRequest extends javax.swing.JPanel {

    /**
     * Creates new form FinanceOrphProcessRequest
     */
   JPanel userProcessContainer;
   UserAccount account;
   FinanceOrphanageOrganization financeOrphanageOrganization;
   Enterprise enterprise;
   EcoSystem business;
   ChildDirectory directory;
    FinanceCCWorkRequest req;
String text;
Child child;
int countApprove=0, countDeny=0;
   public FinanceOrphProcessRequest(JPanel userProcessContainer, UserAccount account, FinanceOrphanageOrganization financeOrphanageOrganization, Enterprise enterprise, EcoSystem business, ChildDirectory directory, FinanceCCWorkRequest req) {
       initComponents();
      
       this.userProcessContainer=userProcessContainer;
   this.account=account;
   this.financeOrphanageOrganization=financeOrphanageOrganization;
  this.enterprise=enterprise;
   this.business=business;
   this.directory=directory;
    this.req=req;
  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        approveBtn = new javax.swing.JButton();
        denybtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Message");

        approveBtn.setText("Approve");
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        denybtn.setText("Deny");
        denybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(denybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(612, 612, 612))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(denybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(332, 332, 332))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
          for(Child ch: directory.getChildList()){
           if(ch.getChildId()==req.getChildId()){
               child = ch;
              String remarks = req.getMessage();
               System.out.println("remarks: "+remarks);
              if(remarks.contains("Bed")){
                  System.out.println("in bed");
                  child.setBed(true);
                  
              }
              if(remarks.contains("Table")){
                       System.out.println("in table");
                  child.setTable(true);
              }
              if(remarks.contains("Closet")){
                       System.out.println("in closet");
                  child.setCloset(true);
              }
           }
       }  
        if(jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter text in the message");
            return;
        }
        text = jTextField1.getText();
        req.setTestResult("Approved");
       req.setMessage(text);
       
     
       
       FinanceWorkAreaJPanel fwajp = new FinanceWorkAreaJPanel(userProcessContainer, account, financeOrphanageOrganization, enterprise, business, directory);
       this.userProcessContainer.add("FinanceWorkAreaJPanel", fwajp);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        countApprove++;
              
    }//GEN-LAST:event_approveBtnActionPerformed

    private void denybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denybtnActionPerformed
         
        if(jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter text in the message");
            return;
        }
        text = jTextField1.getText();
        req.setTestResult("Denied");
       req.setMessage(text);
       
          FinanceWorkAreaJPanel fwajp = new FinanceWorkAreaJPanel(userProcessContainer, account, financeOrphanageOrganization, enterprise, business, directory);
       this.userProcessContainer.add("FinanceWorkAreaJPanel", fwajp);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        countDeny++;
    }//GEN-LAST:event_denybtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton denybtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
